### ISSUE TITLE
Possible bug resulting in misslabled/ordered samples in the "F" table

### ISSUE THREAD

**Issue by timothymillar** [mghamilton/polyAinv#1]
Hi there, 
I noticed when running the published example some samples appear to be mislabeled/ordered in the "F" table of the output. 
Using the code:
```r
library(polyAinv)
load("~/Repo/polyAinv/data/Tab.1.Ham.Kerr.rda", verbose=TRUE)
Tab.1.Ham.Kerr[c("INDIV.ID", "SIRE.GAMETE.PLOIDY", "DAM.GAMETE.PLOIDY")]
```
results in:

<html><body>

INDIV.ID | SIRE.GAMETE.PLOIDY | DAM.GAMETE.PLOIDY
-- | -- | --
1 | 1 | 1
2 | 2 | 2
3 | 0 | 2
4 | 2 | 0
5 | 1 | 1
6 | 2 | 2
7 | 2 | 2
8 | 2 | 2

</body>
</html>

then
```r
results <- polyAinv(ped = Tab.1.Ham.Kerr[,1:7])
results$F
```
results in 

<html><body>

INDIV.ID | PLOIDY | F | K.DIAG | A.DIAG
-- | -- | -- | -- | -- 
1 | 2 | 0.00000000 | 0.5000000 | 1.000000
2 | 4 | 0.07706507 | 0.3077988 | 1.231195
3 | 2 | 0.23119520 | 0.6155976 | 1.231195
4 | 4 | 0.19678603 | 0.3975895 | 1.590358
5 | 2 | 0.04100000 | 0.5205000 | 1.041000
6 | 2 | 0.00000000 | 0.5000000 | 1.000000
7 | 4 | 0.19628593 | 0.3972144 | 1.588858
8 | 4 | 0.19628593 | 0.3972144 | 1.588858

</body>
</html>

Assuming gamete ploidies should sum to the ploidy of the individual then individual 4 should be 2x and individual 6 should be 4x, but this is not how they are shown in the F table.

Based on my calculations this table (excluding the final column) should be:
<html><body>

INDIV.ID | PLOIDY | F | K.DIAG 
-- | -- | -- | -- 
1 | 2 | 0 | 0.5
2 | 4 | 0.077065 |0.3077988
3 | 2 | 0.231195 | 0.6155976
4 | 2 | 0.041 |  0.5205
5 | 2 | 0. | 0.5
6 | 4 | 0.196786 | 0.39758952
7 | 4 | 0.196286 | 0.39721445
8 | 4 | 0.196286 | 0.39721445

</body>
</html>

And this appears to match the diagonal kinships shown in Table 3 of Hamilton and Kerr (2017).
It looks like the sample ordering in the reported table is actually [1,2,3,5,6,4,7,8] but the sample identifiers don't match.

**Comment by mghamilton** [comment]
Hello Tim

I only just noticed your email. My gmail account is more like a junk folder these days. I will look into it. 

Matt

**Comment by mghamilton** [comment]
Hello Tim

You were correct.  There was a sorting issue.  I hope this is now rectified in Version 0.1.3

**Comment by timothymillar** [comment]
Thanks for the quick response @mghamilton! I can confirm i get the expected result with the new version.
